include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true

    # Documentation
    public_member_api_docs: true


    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true

analyzer:
  errors:
    # Treat missing docs as warnings during development, errors before publish
    public_member_api_docs: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
